### ISSUE TITLE
Week 11. Internet & utilities. (29.11)

### ISSUE THREAD

**Issue by ch1pkav** [Myralllka/UCU_Linux_Club#71]
Basics of what networks are. LAN, WAN, DHCP, DNS, etc. How Linux interacts with it all. /etc/hosts/. Linux internet setups & utilities. Crash-course in connecting to the internet. How to connect to WIFI-UCU

Materials:
https://docs.google.com/presentation/d/1jAnxuNJZAIE6TRI_nrOdrDCnhqSRfPf0gPxcnnG2I-E/edit?usp=sharing
https://docs.google.com/document/d/1BwYL-QMpKAGoyavuPf70Wi2Yi_EaYy3zYvZbYA_QuCk/edit?usp=sharing

**Comment by alexg-lviv** [comment]
ну цейго
я лишу оце Basics of what networks are. LAN, WAN, DHCP, DNS, etc.
і розкажу трохи більше про нетворкінг, шо таке айпі, маска мережі, мак адреса, комутатор, маршрутизатор, протоколи, 7-рівнева модель
