### ISSUE TITLE
Website/repo maintenance

### ISSUE THREAD

**Issue by ch1pkav** [Myralllka/UCU_Linux_Club#76]
1. Add links to all the presentations to the corresponding week entries in the [repo](https://github.com/ucu-computer-science/UCU_Linux_Club) and website [homepage](https://ucu-computer-science.github.io/UCU_Linux_Club/):
    - Week 0 Intro [presentation](https://docs.google.com/presentation/d/1d2fPhHRSTY5q5pFCLouLXlm6OVXakXA7kIwOZt0sBGk/edit?usp=drive_link)
    - Week 1.1 Open source [presentation](https://docs.google.com/presentation/d/1aSBcK0A0yJrH1IMCxxX4drk7QP3dpujxViqqINwBNAk/edit?usp=drive_link)
    - Week 1.2 Package managers [presentation](https://docs.google.com/presentation/d/1C3uC4RX_twIeqkJiMsR2CVKXFd8FrTbf-3k1la8Bl30/edit?usp=drive_link)
    - Week 2 CLI [presentation](https://docs.google.com/presentation/d/1bEc8DEu7H1vRGcvSCzmu9x1T-5JqaOHxA5xu4iFRE1Q/edit?usp=drive_link)
    - Week 3 Git, GitHub [presentation](https://docs.google.com/presentation/d/1I7xOQ8g71ydjc_YH-51nBSkcW2Xe2dcL0vSsF_8Yi-8/edit?usp=drive_link)
    - Week 4  Vim + tmux [presentation](https://docs.google.com/presentation/d/1hTp84WBFWUYQAqp0RHHFblVGq5fZ6GImetUR6nqRjUk/edit?usp=drive_link)
    - Week 5.1 LFHS [presentation](https://docs.google.com/presentation/d/1edR7FsbypkGwK_QjP3mhjmL8iKF2Bpf4zeIT40wJSTo/edit?usp=drive_link)
    - Week 5.2 RegEx [presentation](https://docs.google.com/presentation/d/1mMfBrxDmB0FgL9VMl2AsU9Nsc7qbR49S373ZJWKem9U/edit?usp=drive_link)
    - Week 6. Partitions, bootloaders [presentation](https://docs.google.com/presentation/d/1hY0rxAByOzy5Qm36kIMwCJvPLmWLhKBwZDk8aoGulkg/edit?usp=drive_link)
    - Week 7. Filesystems [presentation](https://docs.google.com/presentation/d/1EyS3DytXb4My-BLqjMZkYwpZ4MXTcTcnyam3LIrhIa8/edit?usp=sharing)
    - Week 8. SSH [presentation](https://docs.google.com/presentation/d/1MnKh1AcSWvY9EnFD5U-kDm9Ng43yDOlLVr_pxAYkcN8/edit?usp=drive_link)
    - Week 9. Kernel, systemd (TBD)
 
Check that all of them have rights for viewing by link, outside of UCU domain (a surprising number of people tend to refer to this website outside UCU). Weeks 9-11 are not yet done, so they may go without links for now.

![Image](https://github.com/ucu-computer-science/UCU_Linux_Club/assets/70999143/49cc6acb-21d0-43db-b93b-fe3f71c5f268)

![Image](https://github.com/ucu-computer-science/UCU_Linux_Club/assets/70999143/b35ef9ec-7ebd-4927-99e4-d7815f0f0227)

2. Remove all links to the youtube channel in the repo and website, most importantly from the website footer:

![Image](https://github.com/ucu-computer-science/UCU_Linux_Club/assets/70999143/265a6121-c9e7-40b9-8546-f30821cdb81d)

**Comment by rwmutel** [comment]
done
