### ISSUE TITLE
Week 3 (21.02) - Git continuation

### ISSUE THREAD

**Issue by ch1pkav** [Myralllka/UCU_Linux_Club#87]
Git and Github 2 - originally about git/github features - Projects, organizations, tags/releases, issues, Github Actions (CI/CD) etc. Some more insight on the inner workings of git - commit hashes, merge conflicts, cherry-picking, rebase. Before all this it would be good to start with a small recap of the very basics, maybe in quiz form, as you see fit. Just to make sure everyone is on the same page and knows at least git add, git commit, git push. Also would be good to mention some small useful things, such as .gitignore, integration of Git and your favorite IDE (I really like Jetbrains' wrapper for working with git), etc.

2021 Lecture presentation and notes:
https://docs.google.com/presentation/d/1nOKcDmg70lxg7LNffpw2v_yZnnUvoZc9ydC6jmzKBRU/edit?usp=sharing
https://docs.google.com/document/d/1SnGMw2QpYntnA0EovtS3n-TMrxQj3LpgD-XnzHbDTaU/edit?usp=sharing

They're OK as a starting point, would be good to get more visuals into the presentation, like how exactly the commit tree is formed and modified when each of these operations is performed.

**Comment by Zhukowych** [comment]
Presentation:
https://docs.google.com/presentation/d/1oza8gs0AVF9HL54vJlO_XHdw6Pzws5PhRmbf35CK--c/edit?usp=sharing
